boards/urls.py
from django.urls import path
from . import views

# namespace 에러뜨면 이거 .. 안 한 거다! ㅋㅋ
app_name = 'boards'

urlpatterns = [
    path('', views.index, name='index'),
    path('manage/', views.manage, name='manage'),
    path('service/', views.service, name='service'),
    path('extract/<int:post_pk>/', views.extract, name='extract'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('boards.urls')),
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

boards/models.py
from django.db import models


# Create your models here.


class Post(models.Model):
    category = models.TextField()
    title = models.TextField()
    link = models.TextField()
    thumbnail = models.TextField()  # 해당 필드에 null값이 들어가도 된다
    price = models.TextField()
    # chart = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}. {self.title}'


class Chart(models.Model):
    img = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .crawl import browser_on, href_crawler, image_scrapping
from .models import Post, Chart
from darkflow.net.build import TFNet
from .tablefinder import crop_col_img, split_img, yolo_split, find_table, img_concat
import hashlib
import cv2
import os


# import os
# print(os.getcwd())

# YOLO MODEL LOAD
def load_yolo(load_weight):
    # model은 사용하는 cfg model
    options = {"model": "cfg/size-yolo.cfg",
               "load": load_weight}  # 최신 checkpoint를 load하려면 -1
    tfnet = TFNet(options)
    tfnet.load_from_ckpt()
    return tfnet


load_weight = 31333
tfnet = load_yolo(load_weight)


# Create your views here.


def index(request):
    return render(request, 'boards/index.html')


def service(request):
    query = request.GET.get('query')
    posts = Post.objects.filter(category=query)
    context = {
        'posts': posts,
        'query': query,
    }
    return render(request, 'boards/service.html', context)


def manage(request):
    query = request.GET.get('query')
    browser = browser_on()
    title_list, href_list, src_list, price_list = href_crawler(browser, query, 2)

    # 데이터베이스에 저장
    for (title, thumbnail, link, price) in zip(title_list, src_list, href_list, price_list):
        # DB에 있는지 확인
        if Post.objects.filter(title=title):
            print(f"{title} is already in db")
        else:
            # DB에 없다면 저장!
            post = Post()
            post.category = query
            post.title = title
            post.thumbnail = thumbnail
            post.link = link
            post.price = price
            post.save()

            href = [post.link]
            category = post.category
            hash_object = hashlib.sha1(f"{category}".encode('utf-8'))
            hex_dig = hash_object.hexdigest()
            filename = f"/boards/static/boards/images/screenshot/{hex_dig}_{post.id}.jpg"
            # saves screenshot, no return
            image_scrapping(href, filename, browser)
            img = crop_col_img(filename)
            split_imgs = split_img(img)
            split_imgs = img_concat(split_imgs)

            for idx, slice in enumerate(split_imgs):
                yolo_slice = yolo_split(slice, tfnet)
                if yolo_slice == 0:
                    continue
                tables = find_table(yolo_slice)
                if tables:
                    print(len(tables))
                    for idx2, table in enumerate(tables):
                        tablename = f"C:/STUDY/FindSizeProject/django_app/boards/static/boards/images/tables/" \
                            f"{hex_dig}_{post.id}_{idx}_{idx2}.jpg"
                        print(tablename)
                        print(type(table.img))
                        print(table.img)
                        print(table.img.shape)
                        cv2.imwrite(tablename, table.img)
                        _, tail = os.path.split(tablename)
                        relpath = 'boards/images/tables/' + tail
                        chart = Chart(post_id=post.id, img=relpath)
                        chart.save()

            print(f"{title} 저장!")

    datas = {}
    for (a, b, c, d) in zip(title_list, src_list, href_list, price_list):
        post = Post.objects.filter(title=a)[0]
        datas[a] = [b, c, d, post.id]
    context = {
        'datas': datas,
        'query': query,
    }

    browser.quit()
    return render(request, 'boards/manage.html', context)


def extract(request, post_pk):
    post = get_object_or_404(Post, id=post_pk)
    href = [post.link]
    # OpenCV won't take Korean as filename,
    # so HASHING it so it can.
    category = post.category
    hash_object = hashlib.sha1(f"{category}".encode('utf-8'))
    hex_dig = hash_object.hexdigest()
    filename = f"/boards/static/boards/images/screenshot/{hex_dig}_{post.id}.jpg"
    # saves screenshot, no return
    browser = browser_on()
    image_scrapping(href, filename, browser)
    browser.quit()
    img = crop_col_img(filename)
    split_imgs = split_img(img)
    split_imgs = img_concat(split_imgs)

    for idx, slice in enumerate(split_imgs):
        yolo_slice = yolo_split(slice, tfnet)
        if yolo_slice == 0:
            continue
        tables = find_table(yolo_slice)
        if tables:
            print(len(tables))
            for idx2, table in enumerate(tables):
                tablename = f"C:/STUDY/FindSizeProject/django_app/boards/static/boards/images/tables/" \
                    f"{hex_dig}_{post.id}_{idx}_{idx2}.jpg"
                print(tablename)
                print(type(table.img))
                print(table.img)
                print(table.img.shape)
                cv2.imwrite(tablename, table.img)
                _, tail = os.path.split(tablename)
                relpath = 'boards/images/tables/' + tail
                chart = Chart(post_id=post.id, img=relpath)
                chart.save()

    # post.category = post.category
    # post.title = post.title
    # post.thumbnail = post.thumbnail
    # post.link = post.link
    # post.price = post.price
    #
    # post.save()
    return redirect('boards:index')

boards/templates/boards/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% bootstrap_css %}

    <style>
        .hero-image {
          background: url("{% static 'boards/images/fabric-3506846_1920.jpg' %}") no-repeat center;
          background-size: cover;
          height: 500px;
          position: relative;
          opacity: 0.9;
        }

        .hero-text {
            text-align: center;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            text-shadow: 2px 2px 2px black;
            color:white;
        }

    .carousel-item {
        max-height: 200px;
        min-height: 200px;
    }

    .carousel-control-next, .carousel-control-prev {
        filter: invert(100%);
    }

    /* Pagination links */
    .pagination a {
      color: black;
      float: left;
      padding: 8px 16px;
      text-decoration: none;
      transition: background-color .3s;
    }

    /* Style the active/current link */
    .pagination a.active {
      background-color: dodgerblue;
      color: white;
    }

    /* Add a grey background color on mouse-over */
    .pagination a:hover:not(.active) {background-color: #ddd;}

    /* mag */

        .mag {
        width: 450px;
        margin: 0 auto;
        float: none;
    }

        .mag img {
            max-width: 100%;
        }

    .mag1 {
        width: 120px;
        margin: 0 auto;
        float: none;
    }

        .mag1 img {
            max-width: 100%;
        }

    .mag2 {
        width: 900px;
        margin: 0 auto;
        float: none;
    }

        .mag2 img {
            max-width: 100%;
        }

    .magnify {
        position: relative;
        cursor: none;
    }

    .magnify-large {
        position: absolute;
        display: none;
        width: 500px;
        height: 500px;
        -webkit-box-shadow: 0 0 0 7px rgba(204, 204, 204, 0.55), 0 0 7px 7px rgba(0, 0, 0, 0.25), inset 0 0 40px 2px rgba(0, 0, 0, 0.25);
        -moz-box-shadow: 0 0 0 7px rgba(255, 255, 255, 0.55), 0 0 7px 7px rgba(0, 0, 0, 0.25), inset 0 0 40px 2px rgba(0, 0, 0, 0.25);
        box-shadow: 0 0 0 7px rgba(255, 255, 255, 0.55), 0 0 7px 7px rgba(0, 0, 0, 0.25), inset 0 0 40px 2px rgba(0, 0, 0, 0.25);
        -webkit-border-radius: 100%;
        -moz-border-radius: 100%;
        border-radius: 100%;
    }

    </style>

    <title>CSPpl</title>



</head>
<body>

<div class="hero-image">
    <div class="hero-text">
        <h1>옷찾사</h1>
        <h3>옷을 찾아주는 사람들</h3>
        <form action="{% url 'boards:service' %}">
            {% if query %}
            <input type="text" value="{{ query }}" name="query">
            {% else %}
            <input type="text" name="query">
            {% endif %}
            <input type="submit" value="검색">
        </form>
    </div>
</div>

<div class="container">
    <main>
        <header>
        </header>

        <section>
            <!-- 앞으로 다른 페이지들은 이 content라는 block안에 호출이 된다. -->
            {% block content %}
            {% endblock %}
            <!-- 참고로 content는 걍 이름이니 다르게 지정해줘도 된다. -->


            <div class="pagination d-flex justify-content-center">
              <a href="#">&laquo;</a>
              <a href="#" class="active">1</a>
              <a  href="#">2</a>
              <a href="#">3</a>
              <a href="#">4</a>
              <a href="#">5</a>
              <a href="#">6</a>
              <a href="#">&raquo;</a>
            </div>

        </section>

        <footer>
            <p>Copyright 2019</p>
        </footer>
    </main>
</div>
{% bootstrap_javascript jquery='full' %}



</body>
</html>

boards/templates/boards/index.html
{% extends 'boards/base.html' %} <!-- layout을 상속받는다! -->

{% block content %}

{% endblock %}

boards/templates/boards/manage.html
{% extends 'boards/base.html' %} <!-- layout을 상속받는다! -->

{% block content %}

<hr>

{% if datas %}
{% for key, value in datas.items %}
<div class="row">
    <div class="col-sm-2">
        <img src="{{ value.0 }}" alt="" width="200" height="200" class="img-thumbnail">
    </div>
    <div class="col-sm-3">
        <p>{{ key }}</p>
        <p>price: {{ value.2 }} 원</p>
        <p class="text-truncate">link: {{ value.1 }}</p>
    </div>
    <div class="col-sm-2">
        <a href="{% url 'boards:extract' value.3 %}">[EXTRACT]</a>
    </div>
</div>
{% endfor %}
{% endif %}

{% endblock %}

boards/templates/boards/service.html
{% extends 'boards/base.html' %} <!-- layout을 상속받는다! -->
{% load bootstrap4 %}
{% load static %}

{% block content %}

{% if posts %}
{% for post in posts %}
{% if post.chart_set.all %}

<div class="row">
    <div class="col-sm-3"><img src="{{ post.thumbnail }}" alt="" width="200" height="200" class="img-thumbnail"></div>
    <div class="col-sm-3">
        <p>{{ post.title }}</p>
        <p>price: {{ post.price }} 원</p>
        <a href="{{ post.link }}" target="_blank">[LINK]</a>
    </div>

    <div class="col-sm-6">
        <div id="{{ post.id }}" class="carousel slide">
            <div class="carousel-inner">

                <div class="carousel-item active">  <!--  data-ride="carousel" enables autoslide -->
                    <center>
                        <img class="d-block w-50" src="{% static 'boards/images/LOGO_grey.png' %}" alt="First slide" style="opacity:0.3">
                    </center>
                </div>

                {% for chart in post.chart_set.all %}
                <div class="carousel-item">
                    <a href="{% static chart.img %}" data-toggle="modal" data-target="#m{{ chart.id }}">

                          <img class="d-block w-100" src="{% static chart.img %}" alt="charts">

                    </a>
                </div>

                <!-- Modal -->
                <!-- https://getbootstrap.com/docs/4.3/components/modal/ -->
                <div class="modal fade" id="m{{ chart.id }}" tabindex="-1" role="dialog"
                     aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered" role="document" style="max-width: 65vw;">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalScrollableTitle">Size Table</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body d-flex justify-content-center img-magnifier-container mag1">

                                <img data-toggle="magnify" class="img-responsive img-rounded center-block" style="max-width: 60vw;" src="{% static chart.img %}" alt="charts" id="mag{{ chart.id }}">

                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>

                {% endfor %}

            </div>
            <a class="carousel-control-prev" href="#{{ post.id }}" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#{{ post.id }}" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

    </div>
</div>
{% bootstrap_javascript jquery='full' %}

<!-- http://www.prepbootstrap.com/bootstrap-template/image-magnification -->
<script>
        !function ($) {

        "use strict"; // jshint ;_;

        /* MAGNIFY PUBLIC CLASS DEFINITION
         * =============================== */

        var Magnify = function (element, options) {
            this.init('magnify', element, options)
        }

        Magnify.prototype = {

            constructor: Magnify

            , init: function (type, element, options) {
                var event = 'mousemove'
                    , eventOut = 'mouseleave';

                this.type = type
                this.$element = $(element)
                this.options = this.getOptions(options)
                this.nativeWidth = 0
                this.nativeHeight = 0

                this.$element.wrap('<div class="magnify" >');
                this.$element.parent('.magnify').append('<div class="magnify-large" >');
                this.$element.siblings(".magnify-large").css("background", "url('" + this.$element.attr("src") + "') no-repeat");

                this.$element.parent('.magnify').on(event + '.' + this.type, $.proxy(this.check, this));
                this.$element.parent('.magnify').on(eventOut + '.' + this.type, $.proxy(this.check, this));
            }

            , getOptions: function (options) {
                options = $.extend({}, $.fn[this.type].defaults, options, this.$element.data())

                if (options.delay && typeof options.delay == 'number') {
                    options.delay = {
                        show: options.delay
                        , hide: options.delay
                    }
                }

                return options
            }

            , check: function (e) {
                var container = $(e.currentTarget);
                var self = container.children('img');
                var mag = container.children(".magnify-large");

                // Get the native dimensions of the image
                if (!this.nativeWidth && !this.nativeHeight) {
                    var image = new Image();
                    image.src = self.attr("src");

                    this.nativeWidth = image.width;
                    this.nativeHeight = image.height;

                } else {

                    var magnifyOffset = container.offset();
                    var mx = e.pageX - magnifyOffset.left;
                    var my = e.pageY - magnifyOffset.top;

                    if (mx < container.width() && my < container.height() && mx > 0 && my > 0) {
                        mag.fadeIn(100);
                    } else {
                        mag.fadeOut(100);
                    }

                    if (mag.is(":visible")) {
                        var rx = Math.round(mx / container.width() * this.nativeWidth - mag.width() / 2) * -1;
                        var ry = Math.round(my / container.height() * this.nativeHeight - mag.height() / 2) * -1;
                        var bgp = rx + "px " + ry + "px";

                        var px = mx - mag.width() / 2;
                        var py = my - mag.height() / 2;

                        mag.css({ left: px, top: py, backgroundPosition: bgp });
                    }
                }

            }
        }


        /* MAGNIFY PLUGIN DEFINITION
         * ========================= */

        $.fn.magnify = function (option) {
            return this.each(function () {
                var $this = $(this)
                    , data = $this.data('magnify')
                    , options = typeof option == 'object' && option
                if (!data) $this.data('tooltip', (data = new Magnify(this, options)))
                if (typeof option == 'string') data[option]()
            })
        }

        $.fn.magnify.Constructor = Magnify

        $.fn.magnify.defaults = {
            delay: 0
        }


        /* MAGNIFY DATA-API
         * ================ */

        $(window).on('load', function () {
            $('[data-toggle="magnify"]').each(function () {
                var $mag = $(this);
                $mag.magnify()
            })
        })

    }(window.jQuery);
</script>


{% endif %}
{% endfor %}
{% endif %}

{% endblock %}